### ISSUE TITLE
Support for older Node versions

### ISSUE THREAD

**Issue by StructuralRealist** [scaleway/scaleway-sdk-js#651]
I tried creating a plugin for Strapi for using TEM as the email provider but it was rejected because Strapi supports Node 16 and requires plugins to do so as well. I can imagine this being the case for more frameworks so maybe it's better to support the previous LTS version as well as the current.

**Comment by Vinzius** [comment]
Hi Leon,

Thank you for reaching out and explaining the situation!
I understand that it can be frustrating that you're unable to use our SDK-JS & TEM within Strapi (which supports maintenance LTS).

The reason we moved to Node 18+ was to avoid using an additional package to fetch our API and to natively support certain types like `Blob`.

We're open to suggestions or PRs if you believe there's a clean way to handle this situation in cross environments (Node + Browser). As, in all honesty, we currently don't have the time to address this situation ourselves.

If your primary need is for TEM, you could consider using the [OpenAPI](https://www.scaleway.com/en/developers/static/scaleway.transactional_email.v1alpha1.Api.yml) file of TEM to generate TS types (e.g., with https://github.com/drwpow/openapi-typescript) and manually call the routes you require. Since there should be backward compatibility in the API, it should be safe to use in a plugin.

At some point, we might open-source alternative SDKs (supporting Node 16 for JS). We don't have an ETA yet, but stay tuned. 🙂

Have a great day,
Vincent

**Comment by StructuralRealist** [comment]
Hi Vincent,

Thanks for taking the time to respond, it's much appreciated. I can imagine it being difficult to keep up with all the compatibilities. 

As Strapi supports Node 18 I can use the TEM provider plugin for myself. It's just that Strapi doesn't accept it in their market, which is a shame as it would give some exposure to TEM and Scaleway. 

As they will drop the v16 requirement in September, I don't think it's worth the effort to make the SDK compatible. But maybe it's something to keep in mind for the future, when deciding to drop a Node version.

Thanks for all the hard work and awesome products!

Cheers,
Leon

**Comment by Vinzius** [comment]
Thanks for the precisions!

There is no plan to drop Node 18, as the main reason was for the fetch API + types. But thanks for suggesting, we'll keep that in mind :-) 

Feel free to let us know (message me, or us our community Slack) when your plugin becomes available on Strapi =D

Have a nice week-end,
Vincent
